### ISSUE TITLE
Programming in BASIC 

### ISSUE THREAD

**Issue by freedom7111** [david-schmidt/gsport#15]
Hi!

Could you help me please?

When I program in Prodos Basic, if I give the command HGR2 the screen goes all black and I don't see the command prompt anymore.
If I use the HGR command I see the prompt after I have pressed CTRL+ENTER for many times.

Thank you for an answer!

FD

**Comment by david-schmidt** [comment]
That's exactly what `HGR` and `HGR2` do. `HGR2` is full-screen graphics; you'll never see the prompt. When you switched to `HGR`, your cursor was still near the top of the screen - but by hitting ENTER several times, it made its way down to the 4-line window down at the bottom.

If you want to switch out of graphics mode, `TEXT` will get you back to the text screen. Here's a reasonable summary of Applesoft commands:
https://www.landsnail.com/a2ref.htm

**Comment by wells1632** [comment]
From what I remember, this is by design.

HGR puts you into Hi-Res Graphics mode, with a 3 or 4 line command area at the bottom available for use to run commands.

HGR2 flips you over to the second Hi-Res Graphics mode, which does not have that 4 line area, thus extending your vertical resolution by a number of lines. All that the HGR and HGR2 commands do is turn on these two display modes. To switch back to the full text mode, use the TEXT command. The HGR graphics screen information resides at memory address $2000, and HGR2 resides at $4000.

**Comment by freedom7111** [comment]
Thank you very much!!!

Sorry for my inexperience!

Il giorno mer 21 apr 2021 alle ore 20:28 wells1632 ***@***.***>
ha scritto:
